#ifndef SLAM_SLAM_CHANNELS_HPP
#define SLAM_SLAM_CHANNELS_HPP

#define SLAM_MAP_CHANNEL "SLAM_MAP"
#define SLAM_POSE_CHANNEL "ODOMETRY" //"SLAM_POSE"
#define SLAM_PARTICLES_CHANNEL "SLAM_PARTICLES"

#endif // SLAM_SLAM_CHANNELS_HPP
